language: php

php: 
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install

script:
  - php vendor/bin/phpunit --bootstrap vendor/autoload.php tests/flowTest.php